project:
  type: website
  output-dir: _site

website:
  title: "Preston Smith "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: art.qmd
        text: Art
    background: '#171717'
  page-footer:
    background: '#171717'
    foreground: ' #e400ff'
    border: 'black'
    left:
    - href: index.qmd
      text: Home
      
    right: 
    - icon: github
      href: https://github.com/Poiuy7312
    - icon: linkedin
      href: https://www.linkedin.com/in/preston-smith-5a889134a/


format:
  html:
    theme: [styles.scss]
    mainfont: "sans-serif"
    toc: true



