---
title: "Art"
title-block-banner: True
toc: True
listing:
  contents: art-projects
  id: Posts
  sort: "date desc"
  type: default
  sort-ui: false
  filter-ui: false
  categories: true
page-layout: full
---

## Artist Statement

I create art where you are meant to imagine yourself within the art and the world that it’s supposed to represent. I’m heavily influenced by different fantasy Videogames *Berserk* and on a lesser level differing movie scenes and the emotions they invoke. As a result of this my art and what is included in it is heavily influenced by what I’m interested in at the time.  I’ll often see something in a Videogame or in a movie and wonder what that would look like if it were in the real world or something similar. My process of working is very much thinking about what I want to see in the work and then trying to implement it as best as possible so while it starts with a general Idea it normally evolves into something with other elements to it. I view my process as a form of world building as while it stems from, I think this is cool so I’ll just put it in there. I do normally think about a situation where it would exist within the context of the work. I normally view the work as a somewhat fractured world where different spaces and ideas are interacting and colliding. I like art to be vibrant so I can see the differences more clearly, and it draws my attention to things I wouldn’t normally notice even when I’m the one making it.

## Works

<div id='Posts'></div>
